AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - config/**/*
    - node_modules/**/*
    - tmp/**/*
  NewCops: enable
  TargetRubyVersion: 3.0.1
  
# RSpec tests and rake tasks are expected to have
# large blocks, so exclude them from this cop.
Metrics/BlockLength:
  Max: 125
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'

# Hard to make this pass always and want to keep flexibility
Layout/ArrayAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style:
  Severity: refactor

# It is ok to use inject at times
Style/EachWithObject:
  Enabled: false

Metrics/MethodLength:
  Max: 7

Style/EmptyMethod:
  Enabled: false